name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

permissions:
  contents: write # Add explicit permissions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Updated from v2

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Updated from v2
        with:
          node-version: "20" # Updated to latest LTS
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci
          npm install typescript@latest -g # Ensure TypeScript is available

      - name: Type check
        run: npm run type-check || true # Add type checking step

      - name: Build
        run: npm run build
        env:
          CI: false # Prevents treating warnings as errors

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: null # Remove if you don't have a custom domain
          enable_jekyll: false
